#ifndef TERRAIN_H
#define TERRAIN_H

#include "geometry.h"
#include "heightmap.h"

class Terrain : public Geometry
{
public:
    Terrain(Heightmap map);
protected:
    virtual void fillVertices(QVector<QVector4D> &vertices) override;
    virtual void fillColors(QVector<QVector4D> &colors) override;
    virtual void fillNormals(QVector<QVector3D> &normals, QVector<QVector4D> &vertices) override;
    virtual void render(Drawable *d) override;
private:
    QImage *heightmap;

    //array with vertices generated by heightmap
    QVector<QVector4D> *mesh;
    int meshSize;
};

#endif // TERRAIN_H
